name: Students API pipeline

on:
  push:
    branch: master

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
  listing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: list all files
        run: ls
